// Verylook TYPERT Host manifest — register Remote methods with the
// DSH typert-loader so the api-gateway can route RPCs to this plugin.
/* eslint-disable @typescript-eslint/no-explicit-any */
import { z } from 'zod';

const _any$schema = z.any();

export const TYPERT = {
  package: 'dsh-verylook',
  face: 'host',
  schemas: [],
  model: {
    services: [{
      key: 'verylookRemote',
      exportName: 'VerylookRemoteService',
      description: 'Verylook Remote RPC host service',
      summary: 'Verylook Remote RPC host service',
      tags: [],
      types: [],
      members: [
        { kind: 'method', name: 'describeSettings', signature: 'describeSettings(): Promise<any>', summary: 'Read verylook/vision/audio settings', tags: [] },
        { kind: 'method', name: 'updateSettings', signature: 'updateSettings(payload: any): Promise<any>', summary: 'Update verylook/vision/audio settings', tags: [] },
        { kind: 'method', name: 'describeCredentials', signature: 'describeCredentials(refs: any): Promise<any>', summary: 'List credential refs for providers', tags: [] },
        { kind: 'method', name: 'setCredential', signature: 'setCredential(payload: any): Promise<any>', summary: 'Set a credential value', tags: [] },
        { kind: 'method', name: 'listModels', signature: 'listModels(provider: any): Promise<any>', summary: 'Probe a vision provider for available models', tags: [] },
        { kind: 'method', name: 'upload', signature: 'upload(payload: any): Promise<any>', summary: 'Upload a file into the session uploads dir', tags: [] },
        { kind: 'method', name: 'asrStatus', signature: 'asrStatus(): Promise<any>', summary: 'Check local ASR install status', tags: [] },
        { kind: 'method', name: 'asrInstall', signature: 'asrInstall(payload: any): Promise<any>', summary: 'Start a one-click local ASR install', tags: [] },
        { kind: 'method', name: 'sessionModality', signature: 'sessionModality(sessionId: any): Promise<any>', summary: 'Report whether the session model accepts image input', tags: [] },
        { kind: 'method', name: 'readUpload', signature: 'readUpload(payload: any): Promise<any>', summary: 'Read back an uploaded file', tags: [] },
        { kind: 'method', name: 'envCheck', signature: 'envCheck(): Promise<any>', summary: 'Run environment check', tags: [] },
        { kind: 'method', name: 'envRepair', signature: 'envRepair(action: any): Promise<any>', summary: 'Attempt environment repair', tags: [] },
        { kind: 'method', name: 'capabilityCheck', signature: 'capabilityCheck(): Promise<any>', summary: 'Run full capability check', tags: [] },
        { kind: 'method', name: 'testVision', signature: 'testVision(provider: any): Promise<any>', summary: 'Probe a vision model capability', tags: [] },
        { kind: 'method', name: 'testAudio', signature: 'testAudio(provider: any): Promise<any>', summary: 'Probe an audio model capability', tags: [] },
        { kind: 'method', name: 'getPluginVersion', signature: 'getPluginVersion(): Promise<any>', summary: 'Get plugin version', tags: [] },
        { kind: 'method', name: 'checkUpdate', signature: 'checkUpdate(): Promise<any>', summary: 'Check for plugin updates', tags: [] },
        { kind: 'method', name: 'uninstallPlugin', signature: 'uninstallPlugin(): Promise<any>', summary: 'Uninstall VeryLook plugin config', tags: [] },
      ],
    }],
    types: [],
    events: [],
    objects: [],
  },
  invocations: [
    {
      id: 'dsh-verylook#verylook/describeSettings',
      service: 'verylookRemote', namespace: 'verylook', method: 'describeSettings',
      invocation: { kind: 'direct' }, parameters: [],
      result: { mode: 'strict', typeSymbol: 'VerylookSettingsResult', schema: _any$schema },
    },
    {
      id: 'dsh-verylook#verylook/updateSettings',
      service: 'verylookRemote', namespace: 'verylook', method: 'updateSettings',
      invocation: { kind: 'direct' },
      parameters: [{ name: 'payload', wire: 'payload', source: 'json', codec: { mode: 'strict', typeSymbol: 'VerylookSettingsUpdate', schema: _any$schema } }],
      result: { mode: 'strict', typeSymbol: 'VerylookSettingsUpdateResult', schema: _any$schema },
    },
    {
      id: 'dsh-verylook#verylook/describeCredentials',
      service: 'verylookRemote', namespace: 'verylook', method: 'describeCredentials',
      invocation: { kind: 'direct' },
      parameters: [{ name: 'refs', wire: 'refs', source: 'json', codec: { mode: 'strict', typeSymbol: 'VerylookCredentialRefs', schema: _any$schema } }],
      result: { mode: 'strict', typeSymbol: 'VerylookCredentialsResult', schema: _any$schema },
    },
    {
      id: 'dsh-verylook#verylook/setCredential',
      service: 'verylookRemote', namespace: 'verylook', method: 'setCredential',
      invocation: { kind: 'direct' },
      parameters: [{ name: 'payload', wire: 'payload', source: 'json', codec: { mode: 'strict', typeSymbol: 'VerylookCredentialPayload', schema: _any$schema } }],
      result: { mode: 'strict', typeSymbol: 'VerylookCredentialResult', schema: _any$schema },
    },
    {
      id: 'dsh-verylook#verylook/listModels',
      service: 'verylookRemote', namespace: 'verylook', method: 'listModels',
      invocation: { kind: 'direct' },
      parameters: [{ name: 'provider', wire: 'provider', source: 'json', codec: { mode: 'strict', typeSymbol: 'VisionProviderProbe', schema: _any$schema } }],
      result: { mode: 'strict', typeSymbol: 'VerylookListModelsResult', schema: _any$schema },
    },
    {
      id: 'dsh-verylook#verylook/upload',
      service: 'verylookRemote', namespace: 'verylook', method: 'upload',
      invocation: { kind: 'direct' },
      parameters: [{ name: 'payload', wire: 'payload', source: 'json', codec: { mode: 'strict', typeSymbol: 'VerylookUploadPayload', schema: _any$schema } }],
      result: { mode: 'strict', typeSymbol: 'VerylookUploadResult', schema: _any$schema },
    },
    {
      id: 'dsh-verylook#verylook/asrStatus',
      service: 'verylookRemote', namespace: 'verylook', method: 'asrStatus',
      invocation: { kind: 'direct' }, parameters: [],
      result: { mode: 'strict', typeSymbol: 'VerylookAsrStatus', schema: _any$schema },
    },
    {
      id: 'dsh-verylook#verylook/asrInstall',
      service: 'verylookRemote', namespace: 'verylook', method: 'asrInstall',
      invocation: { kind: 'direct' }, parameters: [],
      result: { mode: 'strict', typeSymbol: 'VerylookAsrInstallResult', schema: _any$schema },
    },
    {
      id: 'dsh-verylook#verylook/sessionModality',
      service: 'verylookRemote', namespace: 'verylook', method: 'sessionModality',
      invocation: { kind: 'direct' },
      parameters: [{ name: 'sessionId', wire: 'sessionId', source: 'json', codec: { mode: 'strict', typeSymbol: 'SessionId', schema: _any$schema } }],
      result: { mode: 'strict', typeSymbol: 'VerylookModalityResult', schema: _any$schema },
    },
    {
      id: 'dsh-verylook#verylook/readUpload',
      service: 'verylookRemote', namespace: 'verylook', method: 'readUpload',
      invocation: { kind: 'direct' },
      parameters: [{ name: 'payload', wire: 'payload', source: 'json', codec: { mode: 'strict', typeSymbol: 'VerylookReadUploadPayload', schema: _any$schema } }],
      result: { mode: 'strict', typeSymbol: 'VerylookReadUploadResult', schema: _any$schema },
    },
    {
      id: 'dsh-verylook#verylook/envCheck',
      service: 'verylookRemote', namespace: 'verylook', method: 'envCheck',
      invocation: { kind: 'direct' }, parameters: [],
      result: { mode: 'strict', typeSymbol: 'VerylookEnvCheckReport', schema: _any$schema },
    },
    {
      id: 'dsh-verylook#verylook/envRepair',
      service: 'verylookRemote', namespace: 'verylook', method: 'envRepair',
      invocation: { kind: 'direct' },
      parameters: [{ name: 'action', wire: 'action', source: 'json', codec: { mode: 'strict', typeSymbol: 'EnvRepairAction', schema: _any$schema } }],
      result: { mode: 'strict', typeSymbol: 'VerylookEnvCheckItem', schema: _any$schema },
    },
    {
      id: 'dsh-verylook#verylook/capabilityCheck',
      service: 'verylookRemote', namespace: 'verylook', method: 'capabilityCheck',
      invocation: { kind: 'direct' }, parameters: [],
      result: { mode: 'strict', typeSymbol: 'VerylookCapabilityReport', schema: _any$schema },
    },
    {
      id: 'dsh-verylook#verylook/testVision',
      service: 'verylookRemote', namespace: 'verylook', method: 'testVision',
      invocation: { kind: 'direct' },
      parameters: [{ name: 'provider', wire: 'provider', source: 'json', codec: { mode: 'strict', typeSymbol: 'TestProviderProbe', schema: _any$schema } }],
      result: { mode: 'strict', typeSymbol: 'VerylookTestVisionResult', schema: _any$schema },
    },
    {
      id: 'dsh-verylook#verylook/testAudio',
      service: 'verylookRemote', namespace: 'verylook', method: 'testAudio',
      invocation: { kind: 'direct' },
      parameters: [{ name: 'provider', wire: 'provider', source: 'json', codec: { mode: 'strict', typeSymbol: 'TestProviderProbe', schema: _any$schema } }],
      result: { mode: 'strict', typeSymbol: 'VerylookTestAudioResult', schema: _any$schema },
    },
    {
      id: 'dsh-verylook#verylook/getPluginVersion',
      service: 'verylookRemote', namespace: 'verylook', method: 'getPluginVersion',
      invocation: { kind: 'direct' }, parameters: [],
      result: { mode: 'strict', typeSymbol: 'VerylookVersionResult', schema: _any$schema },
    },
    {
      id: 'dsh-verylook#verylook/checkUpdate',
      service: 'verylookRemote', namespace: 'verylook', method: 'checkUpdate',
      invocation: { kind: 'direct' }, parameters: [],
      result: { mode: 'strict', typeSymbol: 'VerylookUpdateResult', schema: _any$schema },
    },
    {
      id: 'dsh-verylook#verylook/uninstallPlugin',
      service: 'verylookRemote', namespace: 'verylook', method: 'uninstallPlugin',
      invocation: { kind: 'direct' }, parameters: [],
      result: { mode: 'strict', typeSymbol: 'VerylookUninstallResult', schema: _any$schema },
    },
  ],
};